apiVersion: v1
kind: Service
metadata:
  name: orthanc
  namespace: l10ns
  labels:
    app: orthanc
spec:
  selector:
    app: orthanc  
  ports:
  - name: port-1
    port: 8042
    protocol: TCP
    targetPort: 8042
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orthanc-ss
  namespace: l10ns
  # labels:
  #   hpecp.hpe.com/hpecp-internal-gateway: "true"  # change here for ECP5.1 my-tenant  
spec:
  serviceName: "orthanc"
  replicas: 2
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      containers:
      - name: orthanc
        image: jodogne/orthanc:1.9.2
        ports:
        - containerPort: 8042
          name: port-1
        volumeMounts:
        - name: df-mount
          mountPath: /var/lib/orthanc/db
  volumeClaimTemplates:
  - metadata:
      name: df-mount
    spec:
      storageClassName: managed-nfs-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi